apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-static-pvc
  namespace: bibliotec
  labels:
    app: bibliotec-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: standard
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-media-pvc
  namespace: bibliotec
  labels:
    app: bibliotec-web
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: standard

