# Generated by Django 5.2.7 on 2025-10-04 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_consultation', models.DateTimeField(auto_now_add=True)),
                ('type_action', models.CharField(choices=[('DL', 'Téléchargement'), ('VS', 'Visualisation')], default='DL', max_length=2)),
                ('livre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livres.livre')),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_faites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historique de consultation',
                'ordering': ['-date_consultation'],
            },
        ),
    ]
