# Generated by Django 5.2.7 on 2025-10-05 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livres', '0002_consultation'),
    ]

    operations = [
        migrations.AddField(
            model_name='livre',
            name='annee_publication',
            field=models.IntegerField(blank=True, default=2025, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='discipline',
            field=models.CharField(blank=True, default='Non Spécifiée', help_text='Domaine ou discipline (Ex: Génie Logiciel, Droit, Économie).', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='livre',
            name='type_document',
            field=models.CharField(choices=[('Cours', 'Support de Cours'), ('These', 'Thèse ou Mémoire'), ('Rapport', 'Rapport Interne/Officiel'), ('Livre', 'Livre/Ouvrage')], default='Livre', max_length=20),
        ),
    ]
